<?php

//$caminho = "http://localhost/ctrlEstoque_bckp2/03112020/public/";

$c2 = '';
$caminho = '/';

$var = [
    'caminho_absoluto' => "{$caminho}",
    'nome_app' => 'Controle de Estoque 1.0',
    'nome_logo' => 'Controle de Estoque',
    'top_menu_1' => 'In&iacute;cio',
        'top_menu_1l' => "{$caminho}index",
    'top_menu_2' => 'Seções',
        'top_menu_2l' => "{$caminho}secoes",
    'top_menu_2_1' => 'Seções',
    'top_menu_2_2' => 'Inserir Seção',
    'top_menu_2_3' => 'Editar Seção',
        'top_menu_2_1l' => "{$caminho}secoes",
        'top_menu_2_2l' => "{$caminho}secoes/criar",
        'top_menu_2_3l' => "{$caminho}secoes/editar",
    'top_menu_3' => 'Consultas',
        'top_menu_3l' => "{$caminho}consultas",
    'top_menu_4' => 'Categorias',
    'top_menu_4l' => 'categorias',
    'top_menu_4_1' => 'Exibir Categorias',
    'top_menu_4_2' => 'Inserir Categorias',
    'top_menu_4_3' => 'Editar Categorias',
        'top_menu_4_1l' => "{$caminho}categorias",
        'top_menu_4_2l' => "{$caminho}categorias/criar",
        'top_menu_4_3l' => "{$caminho}categorias/editar",
    'top_menu_5' => 'Administração do Sistema',
        'top_menu_5l' => "{$caminho}admin",
    'top_menu_6' => 'Itens do Estoque',
    'top_menu_6_0' => 'Mostrar Itens',
    'top_menu_6_1' => 'Inserir Item',
    'top_menu_6_2' => 'Alterar Item',
    'top_menu_6_3' => 'Excluir Item',
        'top_menu_6l' => "{$caminho}items",
        'top_menu_6_0l' => "{$caminho}items",
        'top_menu_6_1l' => "{$caminho}items/criar",
        'top_menu_6_2l' => "{$caminho}items/editar",
        'top_menu_6_3l' => "{$caminho}items/delete",
    'top_menu_login' => 'Login',

    'mid_menu_1' => 'Vis&atilde;o Geral',
        'mid_menu_1l' => "{$caminho}",
    'mid_menu_2' => 'Itens Cadastrados',
        'mid_menu_2l' => "{$caminho}",
    'mid_menu_2_1' => '3.592',
    'mid_menu_3' => 'Tipos de Itens',
        'mid_menu_3l' => "{$caminho}",
    'mid_menu_4' => 'Se&ccedil;&otilde;es',
        'mid_menu_4l' => "{$caminho}",
    'mid_menu_5' => 'Setores',
        'mid_menu_5l' => "{$caminho}",
    'mid_menu_6' => 'Categorias',
        'mid_menu_6l' => "{$caminho}categorias",
    'mid_menu_7' => '',
    'side_menu_1' => 'Home',
        'side_menu_1l' => 'Usuários',
    'side_menu_2' => 'Configurações',
        'side_menu_2l' => 'Configurações',
    'side_menu_3' => 'Seções',
        'side_menu_3l' => 'secoes',
    'side_menu_4' => 'Categorias',
        'side_menu_4l' => 'categorias',
    'side_menu_5' => 'Subcategorias',
        'side_menu_5l' => 'subcat',
    'side_menu_6' => 'Marcadores',
        'side_menu_6l' => '',
    '' => '',
    '' => '',

];
$admin = [
    'area_usuario_nome' => "Área do Usuário",
    'area_usuario_link' => "{$caminho}admin/area_usuario",
    'side_menu_1' => 'Usuários',
        'side_menu_1l' => 'Usuários',
    'side_menu_2' => 'Configurações',
        'side_menu_2l' => 'Configurações',
    'side_menu_3' => 'Marcadores',
        'side_menu_3l' => 'Categorias',
    'side_menu_4' => 'Categorias',
        'side_menu_4l' => 'Subcategorias',
    'side_menu_5' => 'Avisos',
        'side_menu_5l' => 'Avisos',
    'side_menu_6' => 'Compras',
        'side_menu_6l' => '',
    '' => '',
    '' => '',
    '' => '',
];

?>
